// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioConvert(arg1, arg2, arg3) {
  return window['go']['main']['App']['AudioConvert'](arg1, arg2, arg3);
}

export function BGMOVIEExtract(arg1, arg2) {
  return window['go']['main']['App']['BGMOVIEExtract'](arg1, arg2);
}

export function DefaultBabelRoot() {
  return window['go']['main']['App']['DefaultBabelRoot']();
}

export function DefaultKFN() {
  return window['go']['main']['App']['DefaultKFN']();
}

export function DetectRealLiveVersion(arg1, arg2) {
  return window['go']['main']['App']['DetectRealLiveVersion'](arg1, arg2);
}

export function DialogueDetectFormat(arg1) {
  return window['go']['main']['App']['DialogueDetectFormat'](arg1);
}

export function DialogueExtractBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DialogueExtractBatch'](arg1, arg2, arg3);
}

export function DialogueExtractFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DialogueExtractFile'](arg1, arg2, arg3);
}

export function DialogueImportBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DialogueImportBatch'](arg1, arg2, arg3, arg4);
}

export function DialogueImportFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DialogueImportFile'](arg1, arg2, arg3, arg4);
}

export function FontEdit(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16) {
  return window['go']['main']['App']['FontEdit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
}

export function FontExtract(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FontExtract'](arg1, arg2, arg3, arg4);
}

export function GetLuckSystemPath() {
  return window['go']['main']['App']['GetLuckSystemPath']();
}

export function ImageBatchExport(arg1, arg2) {
  return window['go']['main']['App']['ImageBatchExport'](arg1, arg2);
}

export function ImageBatchImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImageBatchImport'](arg1, arg2, arg3, arg4);
}

export function ImageExport(arg1, arg2) {
  return window['go']['main']['App']['ImageExport'](arg1, arg2);
}

export function ImageImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImageImport'](arg1, arg2, arg3, arg4);
}

export function MusicPakExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['MusicPakExtract'](arg1, arg2, arg3);
}

export function PakExtract(arg1, arg2) {
  return window['go']['main']['App']['PakExtract'](arg1, arg2);
}

export function PakFontExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['PakFontExtract'](arg1, arg2, arg3);
}

export function PakFontReplace(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['PakFontReplace'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function PakReplace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PakReplace'](arg1, arg2, arg3, arg4);
}

export function RldevArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevArchive'](arg1, arg2, arg3);
}

export function RldevBabelPrepareRuntime(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RldevBabelPrepareRuntime'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RldevBabelWriteHeader(arg1, arg2) {
  return window['go']['main']['App']['RldevBabelWriteHeader'](arg1, arg2);
}

export function RldevCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RldevCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RldevCompileBatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RldevCompileBatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RldevDatJsonToBinary(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevDatJsonToBinary'](arg1, arg2, arg3);
}

export function RldevDatToJson(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevDatToJson'](arg1, arg2, arg3);
}

export function RldevDisassemble(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RldevDisassemble'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RldevExtract(arg1, arg2) {
  return window['go']['main']['App']['RldevExtract'](arg1, arg2);
}

export function RldevG00ToPng(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevG00ToPng'](arg1, arg2, arg3, arg4);
}

export function RldevGanToXml(arg1, arg2) {
  return window['go']['main']['App']['RldevGanToXml'](arg1, arg2);
}

export function RldevList(arg1) {
  return window['go']['main']['App']['RldevList'](arg1);
}

export function RldevNwaToAudio(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevNwaToAudio'](arg1, arg2, arg3, arg4);
}

export function RldevOrgTextExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevOrgTextExport'](arg1, arg2, arg3, arg4);
}

export function RldevOrgTextImport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RldevOrgTextImport'](arg1, arg2, arg3, arg4, arg5);
}

export function RldevPngToG00(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RldevPngToG00'](arg1, arg2, arg3, arg4, arg5);
}

export function RldevSaveBuild(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveBuild'](arg1, arg2, arg3);
}

export function RldevSaveDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveDiff'](arg1, arg2, arg3);
}

export function RldevSaveDoctor(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveDoctor'](arg1, arg2);
}

export function RldevSaveDump(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveDump'](arg1, arg2, arg3);
}

export function RldevSaveExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveExport'](arg1, arg2, arg3);
}

export function RldevSaveGet(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveGet'](arg1, arg2);
}

export function RldevSaveInfo(arg1) {
  return window['go']['main']['App']['RldevSaveInfo'](arg1);
}

export function RldevSaveMap(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveMap'](arg1, arg2);
}

export function RldevSaveSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveSet'](arg1, arg2, arg3);
}

export function RldevXmlToGan(arg1, arg2) {
  return window['go']['main']['App']['RldevXmlToGan'](arg1, arg2);
}

export function ScanGameData() {
  return window['go']['main']['App']['ScanGameData']();
}

export function ScriptCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ScriptCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ScriptDecompile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ScriptDecompile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectOutputDir(arg1) {
  return window['go']['main']['App']['SelectOutputDir'](arg1);
}

export function SelectPakFile() {
  return window['go']['main']['App']['SelectPakFile']();
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}

export function SelectSaveScriptFile(arg1) {
  return window['go']['main']['App']['SelectSaveScriptFile'](arg1);
}

export function SelectSaveTsvFile(arg1) {
  return window['go']['main']['App']['SelectSaveTsvFile'](arg1);
}

export function SelectScriptTxtFile() {
  return window['go']['main']['App']['SelectScriptTxtFile']();
}

export function SelectTsvFile() {
  return window['go']['main']['App']['SelectTsvFile']();
}

export function SetLuckSystemPath() {
  return window['go']['main']['App']['SetLuckSystemPath']();
}

export function SiglusCombinePNG(arg1, arg2) {
  return window['go']['main']['App']['SiglusCombinePNG'](arg1, arg2);
}

export function SiglusDBSBuildFromXLSX(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SiglusDBSBuildFromXLSX'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiglusDBSExportXLSX(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusDBSExportXLSX'](arg1, arg2, arg3);
}

export function SiglusDBSExtract(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SiglusDBSExtract'](arg1, arg2, arg3, arg4, arg5);
}

export function SiglusDBSRebuild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SiglusDBSRebuild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiglusG00ToPng(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SiglusG00ToPng'](arg1, arg2, arg3, arg4);
}

export function SiglusGameexeExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusGameexeExtract'](arg1, arg2, arg3);
}

export function SiglusGameexeRebuild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SiglusGameexeRebuild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiglusLucaBridge(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SiglusLucaBridge'](arg1, arg2, arg3, arg4);
}

export function SiglusMobilePCKExtract(arg1, arg2) {
  return window['go']['main']['App']['SiglusMobilePCKExtract'](arg1, arg2);
}

export function SiglusMobilePCKRebuild(arg1, arg2) {
  return window['go']['main']['App']['SiglusMobilePCKRebuild'](arg1, arg2);
}

export function SiglusOMV2AVI(arg1, arg2) {
  return window['go']['main']['App']['SiglusOMV2AVI'](arg1, arg2);
}

export function SiglusOMVCut(arg1, arg2) {
  return window['go']['main']['App']['SiglusOMVCut'](arg1, arg2);
}

export function SiglusOMVPNG(arg1, arg2) {
  return window['go']['main']['App']['SiglusOMVPNG'](arg1, arg2);
}

export function SiglusOMVPack(arg1, arg2) {
  return window['go']['main']['App']['SiglusOMVPack'](arg1, arg2);
}

export function SiglusPNGVideo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SiglusPNGVideo'](arg1, arg2, arg3, arg4);
}

export function SiglusPngToG00(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SiglusPngToG00'](arg1, arg2, arg3, arg4, arg5);
}

export function SiglusSSDump(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SiglusSSDump'](arg1, arg2, arg3, arg4, arg5);
}

export function SiglusSSDumpAll(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SiglusSSDumpAll'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiglusSSInject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusSSInject'](arg1, arg2, arg3);
}

export function SiglusSSInjectAll(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusSSInjectAll'](arg1, arg2, arg3);
}

export function SiglusSceneExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusSceneExtract'](arg1, arg2, arg3);
}

export function SiglusSceneRebuild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SiglusSceneRebuild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiglusScriptRepack(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiglusScriptRepack'](arg1, arg2, arg3);
}

export function StopProcess() {
  return window['go']['main']['App']['StopProcess']();
}

export function VietnameseFontPatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['VietnameseFontPatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function VoicePakExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['VoicePakExtract'](arg1, arg2, arg3);
}
