// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DefaultBabelRoot():Promise<string>;

export function DefaultKFN():Promise<string>;

export function DialogueDetectFormat(arg1:string):Promise<main.DialogueFormatInfo>;

export function DialogueExtractBatch(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function DialogueExtractFile(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function DialogueImportBatch(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function DialogueImportFile(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function FontEdit(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:number):Promise<string>;

export function FontExtract(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetLuckSystemPath():Promise<string>;

export function ImageBatchExport(arg1:string,arg2:string):Promise<string>;

export function ImageBatchImport(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ImageExport(arg1:string,arg2:string):Promise<string>;

export function ImageImport(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function PakExtract(arg1:string,arg2:string):Promise<string>;

export function PakFontExtract(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PakFontReplace(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function PakReplace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RldevArchive(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RldevBabelPrepareRuntime(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function RldevBabelWriteHeader(arg1:string,arg2:boolean):Promise<string>;

export function RldevCompile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:string):Promise<string>;

export function RldevCompileBatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:string):Promise<string>;

export function RldevDatJsonToBinary(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevDatToJson(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevDisassemble(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<string>;

export function RldevExtract(arg1:string,arg2:string):Promise<string>;

export function RldevG00ToPng(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RldevGanToXml(arg1:string,arg2:string):Promise<string>;

export function RldevList(arg1:string):Promise<string>;

export function RldevNwaToAudio(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RldevPngToG00(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function RldevXmlToGan(arg1:string,arg2:string):Promise<string>;

export function ScanGameData():Promise<Array<main.GamePreset>>;

export function ScriptCompile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function ScriptDecompile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectOutputDir(arg1:string):Promise<string>;

export function SelectPakFile():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectSaveScriptFile(arg1:string):Promise<string>;

export function SelectSaveTsvFile(arg1:string):Promise<string>;

export function SelectScriptTxtFile():Promise<string>;

export function SelectTsvFile():Promise<string>;

export function SetLuckSystemPath():Promise<string>;

export function StopProcess():Promise<void>;
